### ISSUE TITLE
Need to handle additional source parameters

### ISSUE THREAD

**Issue by phundisk** [PagerDuty/chef-sumologic#9]
There are some additional log source parameters which are needed in certain log cases.  One example is the multilineProcessingEnabled flag.

Should include all the possibilities as outlined in their API doc:
https://github.com/SumoLogic/sumo-api-doc/wiki/collector-management-api

**Comment by shortdudey123** [comment]
Solution PR: https://github.com/PagerDuty/chef-sumologic/pull/10

**Comment by shortdudey123** [comment]
Solved by https://github.com/PagerDuty/chef-sumologic/pull/23
